@startuml diagrama_de_clases

class Usuario {

}

class Alerta {
    - leida: boolean
    - tipo: TipoDeAlerta

    + leido()
    + marcar_como_leido()
}

enum TipoDeAlerta {
    URGENTE, INFORMATIVA
}

' puede ser un enum tambien
class Tema {

}

Alerta --> TipoDeAlerta

@enduml